# docker run --rm -d -p 6006:6006 -v "$(${PWD}.Path -replace '\\', '/'):/hh_back" --name hh_back -w /hh_back node:alpine npm run dev
# docker run -it --rm -v "$PWD/server":/hh -v "$PWD/client/build":/hh/build -w /hh -p 80:6006 node:alpine nodemon index.js
#
#$project = $(${PWD}.Path -replace '\\', '/')
# docker run -it -d -v "$(${PWD}.Path -replace '\\','/')/server:/hh" -v "$(${PWD}.Path -replace '\\','/')/client/build:/hh/build" -w /hh -p 6006:6006 --name hh node:alpine npm run dev
#
#
#docker run -it - --name hh -v "$projectPath:/app" -w /app/server -p 6006:6006 node:alpine nodemon index.js